// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function SaveCollections(arg1) {
  return window['go']['main']['App']['SaveCollections'](arg1);
}

export function SendRequest(arg1, arg2) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2);
}
