// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {engine} from '../models';

export function CancelRequest(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function GetCollections():Promise<Array<storage.Collection>>;

export function GetHistory():Promise<Array<storage.HistoryEntry>>;

export function SaveCollections(arg1:Array<storage.Collection>):Promise<void>;

export function SendRequest(arg1:string,arg2:engine.Request):Promise<engine.Response>;
